### ISSUE TITLE
{"message": "Internal server error"} on testing

### ISSUE THREAD

**Issue by korymath** [jacopotagliabue/tensorflow_to_lambda_serverless#1]
Serverless deploys but the error comes back with any prediction.

**Comment by jacopotagliabue** [comment]
Hey! Thanks for writing here! If you followed the steps in the Medium post, the first thing to check is the exact error (as none is expected :-)). How is the error logged on the AWS lambda console?

**Comment by korymath** [comment]
Looks like: Unable to import module 'handler': No module named tensorflow

**Comment by jacopotagliabue** [comment]
Sorry, very basic question: is the library and all dependencies shipped on AWS in the vendored folder?

**Comment by korymath** [comment]
Yes sir. Let me rebuild from scratch and test. Thank you for the quick response.

**Comment by korymath** [comment]
Copy. Rebuild and deploy worked.

**Comment by jacopotagliabue** [comment]
Glad it worked ;-)

**Comment by korymath** [comment]
Thank you again for the great write up and run through. Any cool projects using this?

**Comment by jacopotagliabue** [comment]
Np, anytime! Not sure if I can judge my own coolness :-) but I'm co-founder and CTO of Tooso, an A.I. startup @ the Alchemist and growing in the "AI for search" space. Our website (http://tooso.ai/) does not say much, but if you want to be kept in the loop and/or looking for your next adventure, shoot me an e-mail at jacopo.tagliabue@tooso.ai!
