### ISSUE TITLE
TensorFlow 1.2 on AWS Lambda

### ISSUE THREAD

**Issue by carlthome** [jacopotagliabue/tensorflow_to_lambda_serverless#2]
I see in vendored.zip that [your guide](https://medium.com/tooso/serving-tensorflow-predictions-with-python-and-aws-lambda-facb4ab87ddd) was written for TensorFlow 0.12.1 which is a lot smaller than the latest release (almost doubled in size). In my (brief) experiments with deploying the latest TensorFlow version (1.2) to AWS Lambda I hit the size limits. Can you confirm that this is a problem?

**Comment by jacopotagliabue** [comment]
Hi @carlthome - so sorry to reply just now: for some reasons I haven't seen the notification nor get the email... as for the question: YES, size limits *is* indeed a problem. I'm planning on writing a follow-up with some updated code :-) in the meantime you can check out the "classic" tricks to get down file size, as for example explained here in a similar context: 

https://medium.com/@maebert/machine-learning-on-aws-lambda-5dc57127aee1

make sense?

**Comment by carlthome** [comment]
No worries, @jacopotagliabue! :smiley: 

An updated guide for the latest TensorFlow release on AWS Lambda would be much appreciated. It's hard to figure out what dependencies can be safely deleted without runtime crashes and TensorFlow Lite has only been announced but not released AFAIK.
